spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/webKs?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
server:
  port: 8080
  servlet:
    context-path: /

mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
    map-underscore-to-camel-case: true
logging:
  level:
    com.yjx.web:
      controller: debug
      mapper: debug
      service.impl: info